/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.gui.netbeansGui.Clientes;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.example.interactions.SystemInteractions;
import org.example.tables.Clientes;

/**
 *
 * @author wesle
 */
public class ClientesCadastro extends javax.swing.JFrame {

    SystemInteractions interactions = new SystemInteractions();

    /**
     * Creates new form VendasCadastro
     */
    public ClientesCadastro() {
        initComponents();
    }

    public ClientesCadastro(String cpf, String nome, String telefone, String email) {
        initComponents();

        cpfClientes2.setText(cpf);
        nomeClientes2.setText(nome);
        telefoneClientes2.setText(telefone);
        emailClientes2.setText(email);

        // Adiciona um listener para verificar a cor dos campos de texto ao iniciar a página
        checkInputColor(cpfClientes2);
        checkInputColor(nomeClientes2);
        checkInputColor(telefoneClientes2);
        checkInputColor(emailClientes2);
    }

    private void checkInputColor(JTextField textField) {
        Color grayColor = new Color(204, 204, 204);
        if (textField.getForeground().equals(grayColor)) {
            textField.setForeground(Color.BLACK);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        nomeClientes2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cpfClientes2 = new javax.swing.JTextField();
        emailClientes2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        telefoneClientes2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        nomeClientes1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cpfClientes1 = new javax.swing.JTextField();
        telefoneClientes1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        emailClientes1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Opções");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(955, 590));
        setResizable(false);
        setSize(new java.awt.Dimension(955, 553));

        jPanel1.setBackground(new java.awt.Color(109, 204, 214));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 553));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 540));

        jPanel6.setBackground(new java.awt.Color(235, 235, 235));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nomeClientes2.setForeground(new java.awt.Color(204, 204, 204));
        nomeClientes2.setText("Nome do Cliente");
        nomeClientes2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeClientes2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeClientes2FocusLost(evt);
            }
        });
        nomeClientes2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomeClientes2KeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel13.setText("Nome:");

        jLabel15.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("CPF:");

        cpfClientes2.setForeground(new java.awt.Color(204, 204, 204));
        cpfClientes2.setText("000-000-000-00");
        cpfClientes2.setNextFocusableComponent(nomeClientes2);
        cpfClientes2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpfClientes2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpfClientes2FocusLost(evt);
            }
        });
        cpfClientes2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpfClientes2KeyReleased(evt);
            }
        });

        emailClientes2.setForeground(new java.awt.Color(204, 204, 204));
        emailClientes2.setText("exemplo@ex.com");
        emailClientes2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailClientes2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailClientes2FocusLost(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel16.setText("E-mail:");

        jLabel17.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel17.setText("Telefone:");

        telefoneClientes2.setForeground(new java.awt.Color(204, 204, 204));
        telefoneClientes2.setText("(00) 0 0000-0000");
        telefoneClientes2.setNextFocusableComponent(nomeClientes2);
        telefoneClientes2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefoneClientes2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefoneClientes2FocusLost(evt);
            }
        });
        telefoneClientes2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telefoneClientes2KeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel4.setText("* Obrigatório");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel5.setText("* Obrigatório");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(23, 23, 23))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpfClientes2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(nomeClientes2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefoneClientes2)
                            .addComponent(emailClientes2))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cpfClientes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeClientes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneClientes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailClientes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel14.setText("Editar cliente:");

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setText("Editar");
        jButton2.setBorder(null);
        jButton2.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel22.setText("Cadastrar cliente:");

        jPanel8.setBackground(new java.awt.Color(235, 235, 235));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nomeClientes1.setForeground(new java.awt.Color(204, 204, 204));
        nomeClientes1.setText("Nome do Cliente");
        nomeClientes1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeClientes1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeClientes1FocusLost(evt);
            }
        });
        nomeClientes1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomeClientes1KeyReleased(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel23.setText("Nome:");

        jLabel24.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel24.setText("CPF:");

        cpfClientes1.setForeground(new java.awt.Color(204, 204, 204));
        cpfClientes1.setText("000-000-000-00");
        cpfClientes1.setNextFocusableComponent(nomeClientes2);
        cpfClientes1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpfClientes1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpfClientes1FocusLost(evt);
            }
        });
        cpfClientes1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpfClientes1KeyReleased(evt);
            }
        });

        telefoneClientes1.setForeground(new java.awt.Color(204, 204, 204));
        telefoneClientes1.setText("(00) 0 0000-0000");
        telefoneClientes1.setNextFocusableComponent(nomeClientes2);
        telefoneClientes1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefoneClientes1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefoneClientes1FocusLost(evt);
            }
        });
        telefoneClientes1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telefoneClientes1KeyReleased(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel25.setText("Telefone:");

        jLabel26.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel26.setText("E-mail:");

        emailClientes1.setForeground(new java.awt.Color(204, 204, 204));
        emailClientes1.setText("exemplo@ex.com");
        emailClientes1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailClientes1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailClientes1FocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel2.setText("* Obrigatório");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel3.setText("* Obrigatório");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addComponent(jLabel25))
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeClientes1)
                    .addComponent(telefoneClientes1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addComponent(emailClientes1)
                    .addComponent(cpfClientes1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cpfClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(109, 172, 171));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Voltar");
        jButton4.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoPng.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Opções");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(219, 4));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 292, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ClientesFrame clientesFrame = new ClientesFrame();
        clientesFrame.setVisible(true);
        clientesFrame.pack();
        clientesFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String cpf2 = cpfClientes2.getText();
        String nome2 = nomeClientes2.getText();
        String telefone2 = telefoneClientes2.getText();
        String email2 = emailClientes2.getText();

        if (!cpf2.trim().equals("000-000-000-00") && !nome2.trim().equals("Nome do Cliente")) {
            if (telefone2.trim().equals("(00) 0 0000-0000")) {
                telefone2 = "";
            }

            if (email2.trim().equals("exemplo@ex.com")) {
                email2 = "";
            }

            Clientes cliente = new Clientes(cpf2, nome2, telefone2, email2);

            try {
                Clientes clienteExists = interactions.lerCliente(cpf2);

                if (clienteExists != null) {
                    interactions.atualizarCliente(cliente);

                    // Mensagem a ser exibida
                    String message = "Cliente atualizado com sucesso!";
                    String title = "Sucesso";

                    // Criar botões personalizados
                    Object[] options = {"Voltar", "Permanecer"};

                    // Exibir o JOptionPane com botões personalizados
                    int choice = JOptionPane.showOptionDialog(
                            rootPane, // Componente pai
                            message, // Mensagem
                            title, // Título
                            JOptionPane.YES_NO_OPTION, // Tipo de opção
                            JOptionPane.INFORMATION_MESSAGE, // Tipo de mensagem
                            null, // Ícone
                            options, // Botões personalizados
                            options[0] // Botão padrão
                    );

                    // Ação com base na escolha do usuário
                    if (choice == JOptionPane.YES_OPTION) {
                        // Ação para "Voltar à Tela"
                        ClientesFrame clientesFrame = new ClientesFrame();
                        clientesFrame.setVisible(true);
                        clientesFrame.pack();
                        clientesFrame.setLocationRelativeTo(null);
                        this.dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Cliente não encontrado: O CPF está incorreto.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ClientesCadastro.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Valor inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Existem campos vazios.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cpf1 = cpfClientes1.getText();
        String nome1 = nomeClientes1.getText();
        String telefone1 = telefoneClientes1.getText();
        String email1 = emailClientes1.getText();

        if (!cpf1.trim().equals("000-000-000-00") && !nome1.trim().equals("Nome do Cliente")) {
            if (telefone1.trim().equals("(00) 0 0000-0000")) {
                telefone1 = "";
            }

            if (email1.trim().equals("exemplo@ex.com")) {
                email1 = "";
            }

            Clientes cliente = new Clientes(cpf1, nome1, telefone1, email1);

            try {
                if (cpf1.length() == 14) {
                    interactions.criarCliente(cliente);

                    // Mensagem a ser exibida
                    String message = "Cliente criado com sucesso!";
                    String title = "Sucesso";

                    // Criar botões personalizados
                    Object[] options = {"Voltar", "Permanecer"};

                    // Exibir o JOptionPane com botões personalizados
                    int choice = JOptionPane.showOptionDialog(
                            rootPane, // Componente pai
                            message, // Mensagem
                            title, // Título
                            JOptionPane.YES_NO_OPTION, // Tipo de opção
                            JOptionPane.INFORMATION_MESSAGE, // Tipo de mensagem
                            null, // Ícone
                            options, // Botões personalizados
                            options[0] // Botão padrão
                    );

                    // Ação com base na escolha do usuário
                    if (choice == JOptionPane.YES_OPTION) {
                        // Ação para "Voltar à Tela"
                        ClientesFrame clientesFrame = new ClientesFrame();
                        clientesFrame.setVisible(true);
                        clientesFrame.pack();
                        clientesFrame.setLocationRelativeTo(null);
                        this.dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "CPF inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ClientesCadastro.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Valor inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Existem campos vazios.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cpfClientes1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfClientes1FocusGained
        if (cpfClientes1.getText().equals("000-000-000-00")) {
            cpfClientes1.setText("");
            cpfClientes1.setForeground(Color.black);
        }
    }//GEN-LAST:event_cpfClientes1FocusGained

    private void cpfClientes1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfClientes1FocusLost
        if (cpfClientes1.getText().equals("")) {
            cpfClientes1.setText("000-000-000-00");
            cpfClientes1.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_cpfClientes1FocusLost

    private void cpfClientes1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpfClientes1KeyReleased
        String input = cpfClientes1.getText();

        // Remover todos os caracteres não numéricos
        input = input.replaceAll("[^\\d]", "");

        StringBuilder formattedInput = new StringBuilder(input);

        // Adicionar '-' nos locais corretos do CPF
        if (formattedInput.length() > 3) {
            formattedInput.insert(3, "-");
        }
        if (formattedInput.length() > 7) {
            formattedInput.insert(7, "-");
        }
        if (formattedInput.length() > 11) {
            formattedInput.insert(11, "-");
        }
        // Limitar a 14 caracteres no máximo (000-000-000-00)
        if (formattedInput.length() > 14) {
            formattedInput.setLength(14);
        }

        // Atualizar o conteúdo do jTextField2
        cpfClientes1.setText(formattedInput.toString());

        // Validar o CPF
        if (formattedInput.length() == 14) {
            // Realizar a validação específica do CPF aqui
            // Você pode usar bibliotecas de validação de CPF ou implementar a validação manualmente
        }
    }//GEN-LAST:event_cpfClientes1KeyReleased

    private void cpfClientes2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfClientes2FocusGained
        if (cpfClientes2.getText().equals("000-000-000-00")) {
            cpfClientes2.setText("");
            cpfClientes2.setForeground(Color.black);
        }
    }//GEN-LAST:event_cpfClientes2FocusGained

    private void cpfClientes2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfClientes2FocusLost
        if (cpfClientes2.getText().equals("")) {
            cpfClientes2.setText("000-000-000-00");
            cpfClientes2.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_cpfClientes2FocusLost

    private void cpfClientes2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpfClientes2KeyReleased
        String input = cpfClientes2.getText();

        // Remover todos os caracteres não numéricos
        input = input.replaceAll("[^\\d]", "");

        StringBuilder formattedInput = new StringBuilder(input);

        // Adicionar '-' nos locais corretos do CPF
        if (formattedInput.length() > 3) {
            formattedInput.insert(3, "-");
        }
        if (formattedInput.length() > 7) {
            formattedInput.insert(7, "-");
        }
        if (formattedInput.length() > 11) {
            formattedInput.insert(11, "-");
        }
        // Limitar a 14 caracteres no máximo (000-000-000-00)
        if (formattedInput.length() > 14) {
            formattedInput.setLength(14);
        }

        // Atualizar o conteúdo do jTextField2
        cpfClientes2.setText(formattedInput.toString());

        // Validar o CPF
        if (formattedInput.length() == 14) {
            // Realizar a validação específica do CPF aqui
            // Você pode usar bibliotecas de validação de CPF ou implementar a validação manualmente
        }
    }//GEN-LAST:event_cpfClientes2KeyReleased

    private void nomeClientes1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeClientes1FocusGained
        if (nomeClientes1.getText().equals("Nome do Cliente")) {
            nomeClientes1.setText("");
            nomeClientes1.setForeground(Color.black);
        }
    }//GEN-LAST:event_nomeClientes1FocusGained

    private void nomeClientes1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeClientes1FocusLost
        if (nomeClientes1.getText().equals("")) {
            nomeClientes1.setText("Nome do Cliente");
            nomeClientes1.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_nomeClientes1FocusLost

    private void nomeClientes1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeClientes1KeyReleased
        String input = nomeClientes1.getText();

        // Remover todos os caracteres não alfabéticos
        input = input.replaceAll("[^\\p{L} ]", "");
        nomeClientes1.setText(input);
    }//GEN-LAST:event_nomeClientes1KeyReleased

    private void telefoneClientes1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefoneClientes1FocusGained
        if (telefoneClientes1.getText().equals("(00) 0 0000-0000")) {
            telefoneClientes1.setText("");
            telefoneClientes1.setForeground(Color.black);
        }
    }//GEN-LAST:event_telefoneClientes1FocusGained

    private void telefoneClientes1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefoneClientes1FocusLost
        if (telefoneClientes1.getText().equals("")) {
            telefoneClientes1.setText("(00) 0 0000-0000");
            telefoneClientes1.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_telefoneClientes1FocusLost

    private void telefoneClientes2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefoneClientes2FocusGained
        if (telefoneClientes2.getText().equals("(00) 0 0000-0000")) {
            telefoneClientes2.setText("");
            telefoneClientes2.setForeground(Color.black);
        }
    }//GEN-LAST:event_telefoneClientes2FocusGained

    private void telefoneClientes2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefoneClientes2FocusLost
        if (telefoneClientes2.getText().equals("")) {
            telefoneClientes2.setText("(00) 0 0000-0000");
            telefoneClientes2.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_telefoneClientes2FocusLost

    private void emailClientes1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailClientes1FocusGained
        if (emailClientes1.getText().equals("exemplo@ex.com")) {
            emailClientes1.setText("");
            emailClientes1.setForeground(Color.black);
        }
    }//GEN-LAST:event_emailClientes1FocusGained

    private void emailClientes1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailClientes1FocusLost
        String input = emailClientes1.getText();

        // Validar formato de email
        if (!isValidEmail(input)) {
            JOptionPane.showMessageDialog(null, "Email inválido! O formato deve ser 'email@email.com'.");
            emailClientes1.setText("exemplo@ex.com");
            emailClientes1.setForeground(new Color(204, 204, 204));
        }

        if (emailClientes1.getText().equals("")) {
            emailClientes1.setText("exemplo@ex.com");
            emailClientes1.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_emailClientes1FocusLost

    private void emailClientes2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailClientes2FocusGained
        if (emailClientes2.getText().equals("exemplo@ex.com")) {
            emailClientes2.setText("");
            emailClientes2.setForeground(Color.black);
        }
    }//GEN-LAST:event_emailClientes2FocusGained

    private void emailClientes2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailClientes2FocusLost

        String input = emailClientes2.getText();

        // Validar formato de email
        if (!isValidEmail(input)) {
            JOptionPane.showMessageDialog(null, "Email inválido! O formato deve ser 'email@email.com'.");
            emailClientes2.setText("exemplo@ex.com");
            emailClientes2.setForeground(new Color(204, 204, 204));
        }

        if (emailClientes2.getText().equals("")) {
            emailClientes2.setText("exemplo@ex.com");
            emailClientes2.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_emailClientes2FocusLost

    private void nomeClientes2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeClientes2FocusGained
        if (nomeClientes2.getText().equals("Nome do Cliente")) {
            nomeClientes2.setText("");
            nomeClientes2.setForeground(Color.black);
        }
    }//GEN-LAST:event_nomeClientes2FocusGained

    private void nomeClientes2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeClientes2FocusLost
        if (nomeClientes2.getText().equals("")) {
            nomeClientes2.setText("Nome do Cliente");
            nomeClientes2.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_nomeClientes2FocusLost

    private void nomeClientes2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeClientes2KeyReleased
        String input = nomeClientes2.getText();

        // Remover todos os caracteres não alfabéticos
        input = input.replaceAll("[^\\p{L} ]", "");
        nomeClientes2.setText(input);
    }//GEN-LAST:event_nomeClientes2KeyReleased

    private void telefoneClientes1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefoneClientes1KeyReleased
        String input = telefoneClientes1.getText();

        // Remover todos os caracteres não numéricos
        input = input.replaceAll("[^\\d]", "");

        StringBuilder formattedInput = new StringBuilder(input);

        // Adicionar parênteses, espaço e traço nos locais corretos do telefone
        if (formattedInput.length() > 0) {
            formattedInput.insert(0, "(");
        }
        if (formattedInput.length() > 3) {
            formattedInput.insert(3, ") ");
        }

        // Limitar a 15 caracteres no máximo ((00) 0 0000-0000)
        if (formattedInput.length() > 14) {
            formattedInput.setLength(14);
        }

        // Atualizar o conteúdo do jTextField2
        telefoneClientes1.setText(formattedInput.toString());
    }//GEN-LAST:event_telefoneClientes1KeyReleased

    private void telefoneClientes2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefoneClientes2KeyReleased
        String input = telefoneClientes2.getText();

        // Remover todos os caracteres não numéricos
        input = input.replaceAll("[^\\d]", "");

        StringBuilder formattedInput = new StringBuilder(input);

        // Adicionar parênteses, espaço e traço nos locais corretos do telefone
        if (formattedInput.length() > 0) {
            formattedInput.insert(0, "(");
        }
        if (formattedInput.length() > 3) {
            formattedInput.insert(3, ") ");
        }

        // Limitar a 15 caracteres no máximo ((00) 0 0000-0000)
        if (formattedInput.length() > 14) {
            formattedInput.setLength(14);
        }

        // Atualizar o conteúdo do jTextField2
        telefoneClientes2.setText(formattedInput.toString());
    }//GEN-LAST:event_telefoneClientes2KeyReleased

    private static boolean isValidEmail(String email) {
        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
        return email.matches(emailRegex);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientesCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpfClientes1;
    private javax.swing.JTextField cpfClientes2;
    private javax.swing.JTextField emailClientes1;
    private javax.swing.JTextField emailClientes2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField nomeClientes1;
    private javax.swing.JTextField nomeClientes2;
    private javax.swing.JTextField telefoneClientes1;
    private javax.swing.JTextField telefoneClientes2;
    // End of variables declaration//GEN-END:variables
}
