/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.gui.netbeansGui.Produtos;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.example.gui.netbeansGui.FirstOptions;
import org.example.interactions.SystemInteractions;
import org.example.tables.Produtos;

/**
 *
 * @author wesle
 */
public class ProdutosCadastro extends javax.swing.JFrame {

    SystemInteractions interactions = new SystemInteractions();

    /**
     * Creates new form VendasCadastro
     */
    public ProdutosCadastro() {
        initComponents();
    }

    public ProdutosCadastro(Integer id, String nome, Double valor, Integer qtd, String desc) {
        initComponents();

        idProduto1.setText(id.toString());
        nomeProduto2.setText(nome);
        valorProduto2.setText(valor.toString());
        quantidadeProduto2.setText(qtd.toString());
        descricaoProduto2.setText(desc);

        idProduto2.setText(id.toString());
        
        checkInputColor(idProduto1);
        checkInputColor(nomeProduto2);
        checkInputColor(valorProduto2);
        checkInputColor(quantidadeProduto2);
        checkInputColor(descricaoProduto2);
        
        checkInputColor(idProduto2);
    }
    
    private void checkInputColor(JTextField textField) {
        Color grayColor = new Color(204, 204, 204);
        if (textField.getForeground().equals(grayColor)) {
            textField.setForeground(Color.BLACK);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        valorProduto1 = new javax.swing.JTextField();
        quantidadeProduto1 = new javax.swing.JTextField();
        descricaoProduto1 = new javax.swing.JTextField();
        nomeProduto1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        valorProduto2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        quantidadeProduto2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        descricaoProduto2 = new javax.swing.JTextField();
        nomeProduto2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        idProduto1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        idProduto2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Opções");
        setPreferredSize(new java.awt.Dimension(1220, 655));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 5710));

        jPanel1.setBackground(new java.awt.Color(109, 204, 214));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 560));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 600));

        jPanel3.setBackground(new java.awt.Color(235, 235, 235));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        valorProduto1.setForeground(new java.awt.Color(204, 204, 204));
        valorProduto1.setText("0");
        valorProduto1.setNextFocusableComponent(quantidadeProduto1);
        valorProduto1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valorProduto1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                valorProduto1FocusLost(evt);
            }
        });
        valorProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorProduto1ActionPerformed(evt);
            }
        });
        valorProduto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valorProduto1KeyReleased(evt);
            }
        });

        quantidadeProduto1.setForeground(new java.awt.Color(204, 204, 204));
        quantidadeProduto1.setText("0");
        quantidadeProduto1.setNextFocusableComponent(descricaoProduto1);
        quantidadeProduto1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                quantidadeProduto1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                quantidadeProduto1FocusLost(evt);
            }
        });
        quantidadeProduto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantidadeProduto1KeyReleased(evt);
            }
        });

        descricaoProduto1.setForeground(new java.awt.Color(204, 204, 204));
        descricaoProduto1.setText("Descrição do Produto");
        descricaoProduto1.setToolTipText("");
        descricaoProduto1.setNextFocusableComponent(nomeProduto1);
        descricaoProduto1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descricaoProduto1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                descricaoProduto1FocusLost(evt);
            }
        });
        descricaoProduto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descricaoProduto1KeyReleased(evt);
            }
        });

        nomeProduto1.setForeground(new java.awt.Color(204, 204, 204));
        nomeProduto1.setText("Nome do Produto");
        nomeProduto1.setNextFocusableComponent(valorProduto1);
        nomeProduto1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeProduto1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeProduto1FocusLost(evt);
            }
        });
        nomeProduto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomeProduto1KeyReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel17.setText("Nome:");

        jLabel22.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel22.setText("Valor:");

        jLabel23.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel23.setText("Quantidade:");

        jLabel24.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel24.setText("Descrição:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantidadeProduto1)
                    .addComponent(nomeProduto1)
                    .addComponent(descricaoProduto1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(valorProduto1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(valorProduto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quantidadeProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(descricaoProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(17, 17, 17))
        );

        jButton1.setBackground(new java.awt.Color(109, 172, 171));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel8.setText("Registrar novo produto:");

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setText("Excluir");
        jButton3.setBorder(null);
        jButton3.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(235, 235, 235));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        valorProduto2.setForeground(new java.awt.Color(204, 204, 204));
        valorProduto2.setText("0");
        valorProduto2.setNextFocusableComponent(quantidadeProduto2);
        valorProduto2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valorProduto2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                valorProduto2FocusLost(evt);
            }
        });
        valorProduto2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valorProduto2KeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel7.setText("Valor:");

        jLabel11.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel11.setText("Quantidade:");

        quantidadeProduto2.setForeground(new java.awt.Color(204, 204, 204));
        quantidadeProduto2.setText("0");
        quantidadeProduto2.setNextFocusableComponent(descricaoProduto2);
        quantidadeProduto2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                quantidadeProduto2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                quantidadeProduto2FocusLost(evt);
            }
        });
        quantidadeProduto2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantidadeProduto2KeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel12.setText("Descrição:");

        descricaoProduto2.setForeground(new java.awt.Color(204, 204, 204));
        descricaoProduto2.setText("Descrição do Produto");
        descricaoProduto2.setNextFocusableComponent(idProduto1);
        descricaoProduto2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descricaoProduto2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                descricaoProduto2FocusLost(evt);
            }
        });
        descricaoProduto2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descricaoProduto2KeyReleased(evt);
            }
        });

        nomeProduto2.setForeground(new java.awt.Color(204, 204, 204));
        nomeProduto2.setText("Nome do Produto");
        nomeProduto2.setNextFocusableComponent(valorProduto2);
        nomeProduto2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeProduto2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeProduto2FocusLost(evt);
            }
        });
        nomeProduto2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomeProduto2KeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel13.setText("Nome:");

        jLabel15.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel15.setText("ID:");

        idProduto1.setForeground(new java.awt.Color(204, 204, 204));
        idProduto1.setText("0");
        idProduto1.setNextFocusableComponent(nomeProduto2);
        idProduto1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idProduto1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idProduto1FocusLost(evt);
            }
        });
        idProduto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idProduto1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idProduto1)
                    .addComponent(valorProduto2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomeProduto2)
                    .addComponent(quantidadeProduto2)
                    .addComponent(descricaoProduto2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadeProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricaoProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel14.setText("Editar produto:");

        jLabel16.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel16.setText("Excluir produto:");

        jPanel7.setBackground(new java.awt.Color(235, 235, 235));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel21.setText("ID:");

        idProduto2.setForeground(new java.awt.Color(204, 204, 204));
        idProduto2.setText("0");
        idProduto2.setNextFocusableComponent(idProduto2);
        idProduto2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idProduto2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idProduto2FocusLost(evt);
            }
        });
        idProduto2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idProduto2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(idProduto2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setText("Editar");
        jButton2.setBorder(null);
        jButton2.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Voltar");
        jButton4.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoPng.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Opções");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome1 = nomeProduto1.getText();
        String desc1 = descricaoProduto1.getText();
        Double valor1 = null;
        Integer qtd1 = null;

        if (!valorProduto1.getText().trim().equals("0")) {
            valor1 = Double.valueOf(valorProduto1.getText());
        }

        if (!quantidadeProduto1.getText().trim().equals("0")) {
            qtd1 = Integer.valueOf(quantidadeProduto1.getText());
        }

        if (valor1 != null && qtd1 != null && !nome1.trim().equals("Nome do Produto") && !desc1.trim().equals("Descrição do Produto")) {
            Produtos produtos = new Produtos(valor1, qtd1, nome1, desc1);

            try {
                interactions.criarProduto(produtos);

                // Mensagem a ser exibida
                String message = "Produto cadastrado com sucesso!";
                String title = "Sucesso";

                // Criar botões personalizados
                Object[] options = {"Voltar", "Permanecer"};

                // Exibir o JOptionPane com botões personalizados
                int choice = JOptionPane.showOptionDialog(
                        rootPane, // Componente pai
                        message, // Mensagem
                        title, // Título
                        JOptionPane.YES_NO_OPTION, // Tipo de opção
                        JOptionPane.INFORMATION_MESSAGE, // Tipo de mensagem
                        null, // Ícone
                        options, // Botões personalizados
                        options[0] // Botão padrão
                );

                // Ação com base na escolha do usuário
                if (choice == JOptionPane.YES_OPTION) {
                    // Ação para "Voltar à Tela"
                    ProdutosFrame produtosFrame = new ProdutosFrame();
                    produtosFrame.setVisible(true);
                    produtosFrame.pack();
                    produtosFrame.setLocationRelativeTo(null);
                    this.dispose();
                }
            } catch (SQLException ex) {
                Logger.getLogger(ProdutosCadastro.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Valor inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Existem campos vazios.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ProdutosFrame produtosFrame = new ProdutosFrame();
        produtosFrame.setVisible(true);
        produtosFrame.pack();
        produtosFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Integer id2 = null;

        if (!idProduto2.getText().trim().equals("0")) {
            id2 = Integer.valueOf(idProduto2.getText());
        }

        if (id2 != null) {
            try {
                Produtos produto = interactions.lerProduto(id2);
                if (produto != null) {
                    interactions.excluirProduto(id2);

                    // Mensagem a ser exibida
                    String message = "Produto excluido com sucesso!";
                    String title = "Sucesso";

                    // Criar botões personalizados
                    Object[] options = {"Voltar", "Permanecer"};

                    // Exibir o JOptionPane com botões personalizados
                    int choice = JOptionPane.showOptionDialog(
                            rootPane, // Componente pai
                            message, // Mensagem
                            title, // Título
                            JOptionPane.YES_NO_OPTION, // Tipo de opção
                            JOptionPane.INFORMATION_MESSAGE, // Tipo de mensagem
                            null, // Ícone
                            options, // Botões personalizados
                            options[0] // Botão padrão
                    );

                    // Ação com base na escolha do usuário
                    if (choice == JOptionPane.YES_OPTION) {
                        // Ação para "Voltar à Tela"
                        ProdutosFrame produtosFrame = new ProdutosFrame();
                        produtosFrame.setVisible(true);
                        produtosFrame.pack();
                        produtosFrame.setLocationRelativeTo(null);
                        this.dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Produto não encontrado: O ID está incorreto.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ProdutosCadastro.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Erro ao excluir!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Existem campos vazios.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Integer id1 = null;
        Double valor2 = null;
        Integer qtd2 = null;

        String nome2 = nomeProduto2.getText();
        String desc2 = descricaoProduto2.getText();

        if (!idProduto1.getText().trim().equals("0")) {
            id1 = Integer.valueOf(idProduto1.getText());
        }

        if (!valorProduto2.getText().trim().equals("0")) {
            valor2 = Double.valueOf(valorProduto2.getText());
        }

        if (!quantidadeProduto2.getText().trim().equals("0")) {
            qtd2 = Integer.valueOf(quantidadeProduto2.getText());
        }

        if (id1 != null && valor2 != null && qtd2 != null && !nome2.trim().equals("Nome do Produto") && !desc2.trim().equals("Descrição do Produto")) {
            Produtos produtos = new Produtos(id1, valor2, qtd2, nome2, desc2);
            try {
                Produtos produtosExists = interactions.lerProduto(id1);

                if (produtosExists != null) {
                    try {
                        if (qtd2 < 0) {
                            throw new IllegalArgumentException("Quantidade não pode ser menor que 0.");
                        }
                        interactions.atualizarProduto(produtos);

                        // Mensagem a ser exibida
                        String message = "Produto atualizado com sucesso!";
                        String title = "Sucesso";

                        // Criar botões personalizados
                        Object[] options = {"Voltar", "Permanecer"};

                        // Exibir o JOptionPane com botões personalizados
                        int choice = JOptionPane.showOptionDialog(
                                rootPane, // Componente pai
                                message, // Mensagem
                                title, // Título
                                JOptionPane.YES_NO_OPTION, // Tipo de opção
                                JOptionPane.INFORMATION_MESSAGE, // Tipo de mensagem
                                null, // Ícone
                                options, // Botões personalizados
                                options[0] // Botão padrão
                        );

                        // Ação com base na escolha do usuário
                        if (choice == JOptionPane.YES_OPTION) {
                            // Ação para "Voltar à Tela"
                            ProdutosFrame produtosFrame = new ProdutosFrame();
                            produtosFrame.setVisible(true);
                            produtosFrame.pack();
                            produtosFrame.setLocationRelativeTo(null);
                            this.dispose();
                        }
                    } catch (IllegalArgumentException ex) {
                        JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    throw new IllegalArgumentException("Produto não encontrado: O ID está incorreto.");
                }

            } catch (SQLException ex) {
                Logger.getLogger(ProdutosCadastro.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Valor inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
            } catch (IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Existem campos vazios.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nomeProduto1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeProduto1FocusGained
        if (nomeProduto1.getText().equals("Nome do Produto")) {
            nomeProduto1.setText("");
            nomeProduto1.setForeground(Color.black);
        }
    }//GEN-LAST:event_nomeProduto1FocusGained

    private void nomeProduto1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeProduto1FocusLost
        if (nomeProduto1.getText().equals("")) {
            nomeProduto1.setText("Nome do Produto");
            nomeProduto1.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_nomeProduto1FocusLost

    private void nomeProduto1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeProduto1KeyReleased
        String input = nomeProduto1.getText();

        // Remover todos os caracteres não alfabéticos
        input = input.replaceAll("[^\\p{L} ]", "");
        nomeProduto1.setText(input);
    }//GEN-LAST:event_nomeProduto1KeyReleased

    private void valorProduto1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorProduto1FocusGained
        if (valorProduto1.getText().equals("0")) {
            valorProduto1.setText("");
            valorProduto1.setForeground(Color.black);
        }
    }//GEN-LAST:event_valorProduto1FocusGained

    private void valorProduto1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorProduto1FocusLost
        if (valorProduto1.getText().equals("")) {
            valorProduto1.setText("0");
            valorProduto1.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_valorProduto1FocusLost

    private void valorProduto1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorProduto1KeyReleased
        String input = valorProduto1.getText();

        // Remover todos os caracteres não numéricos
        input = input.replaceAll("[^\\d.,]", "");
        valorProduto1.setText(input);
    }//GEN-LAST:event_valorProduto1KeyReleased

    private void quantidadeProduto1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantidadeProduto1KeyReleased
        String input = quantidadeProduto1.getText();

        // Remover todos os caracteres não numéricos
        input = input.replaceAll("[^\\d]", "");
        quantidadeProduto1.setText(input);
    }//GEN-LAST:event_quantidadeProduto1KeyReleased

    private void quantidadeProduto1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantidadeProduto1FocusGained
        if (quantidadeProduto1.getText().equals("0")) {
            quantidadeProduto1.setText("");
            quantidadeProduto1.setForeground(Color.black);
        }
    }//GEN-LAST:event_quantidadeProduto1FocusGained

    private void quantidadeProduto1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantidadeProduto1FocusLost
        if (quantidadeProduto1.getText().equals("")) {
            quantidadeProduto1.setText("0");
            quantidadeProduto1.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_quantidadeProduto1FocusLost

    private void descricaoProduto1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descricaoProduto1FocusGained
        if (descricaoProduto1.getText().equals("Descrição do Produto")) {
            descricaoProduto1.setText("");
            descricaoProduto1.setForeground(Color.black);
        }
    }//GEN-LAST:event_descricaoProduto1FocusGained

    private void descricaoProduto1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descricaoProduto1FocusLost
        if (descricaoProduto1.getText().equals("")) {
            descricaoProduto1.setText("Descrição do Produto");
            descricaoProduto1.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_descricaoProduto1FocusLost

    private void descricaoProduto1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descricaoProduto1KeyReleased
        String input = descricaoProduto1.getText();

        // Remover todos os caracteres não alfabéticos
        input = input.replaceAll("[^\\p{L} ]", "");
        descricaoProduto1.setText(input);
    }//GEN-LAST:event_descricaoProduto1KeyReleased

    private void idProduto1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idProduto1FocusGained
        if (idProduto1.getText().equals("0")) {
            idProduto1.setText("");
            idProduto1.setForeground(Color.black);
        }
    }//GEN-LAST:event_idProduto1FocusGained

    private void idProduto1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idProduto1FocusLost
        if (idProduto1.getText().equals("")) {
            idProduto1.setText("0");
            idProduto1.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_idProduto1FocusLost

    private void idProduto1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idProduto1KeyReleased
        String input = idProduto1.getText();

        // Remover todos os caracteres não numéricos
        input = input.replaceAll("[^\\d]", "");
        idProduto1.setText(input);
    }//GEN-LAST:event_idProduto1KeyReleased

    private void nomeProduto2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeProduto2FocusGained
        if (nomeProduto2.getText().equals("Nome do Produto")) {
            nomeProduto2.setText("");
            nomeProduto2.setForeground(Color.black);
        }
    }//GEN-LAST:event_nomeProduto2FocusGained

    private void nomeProduto2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeProduto2FocusLost
        if (nomeProduto2.getText().equals("")) {
            nomeProduto2.setText("Nome do Produto");
            nomeProduto2.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_nomeProduto2FocusLost

    private void nomeProduto2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeProduto2KeyReleased
        String input = nomeProduto2.getText();

        // Remover todos os caracteres não alfabéticos
        input = input.replaceAll("[^\\p{L} ]", "");
        nomeProduto2.setText(input);
    }//GEN-LAST:event_nomeProduto2KeyReleased

    private void valorProduto2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorProduto2FocusGained
        if (valorProduto2.getText().equals("0")) {
            valorProduto2.setText("");
            valorProduto2.setForeground(Color.black);
        }
    }//GEN-LAST:event_valorProduto2FocusGained

    private void valorProduto2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorProduto2KeyReleased
        String input = valorProduto2.getText();

        // Remover todos os caracteres não numéricos
        input = input.replaceAll("[^\\d.,]", "");
        valorProduto2.setText(input);
    }//GEN-LAST:event_valorProduto2KeyReleased

    private void valorProduto2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorProduto2FocusLost
        if (valorProduto2.getText().equals("")) {
            valorProduto2.setText("0");
            valorProduto2.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_valorProduto2FocusLost

    private void quantidadeProduto2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantidadeProduto2FocusGained
        if (quantidadeProduto2.getText().equals("0")) {
            quantidadeProduto2.setText("");
            quantidadeProduto2.setForeground(Color.black);
        }
    }//GEN-LAST:event_quantidadeProduto2FocusGained

    private void quantidadeProduto2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantidadeProduto2FocusLost
        if (quantidadeProduto2.getText().equals("")) {
            quantidadeProduto2.setText("0");
            quantidadeProduto2.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_quantidadeProduto2FocusLost

    private void quantidadeProduto2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantidadeProduto2KeyReleased
        String input = quantidadeProduto2.getText();

        // Remover todos os caracteres não numéricos
        input = input.replaceAll("[^\\d]", "");
        quantidadeProduto2.setText(input);
    }//GEN-LAST:event_quantidadeProduto2KeyReleased

    private void descricaoProduto2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descricaoProduto2FocusGained
        if (descricaoProduto2.getText().equals("Descrição do Produto")) {
            descricaoProduto2.setText("");
            descricaoProduto2.setForeground(Color.black);
        }
    }//GEN-LAST:event_descricaoProduto2FocusGained

    private void descricaoProduto2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descricaoProduto2FocusLost
        if (descricaoProduto2.getText().equals("")) {
            descricaoProduto2.setText("Descrição do Produto");
            descricaoProduto2.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_descricaoProduto2FocusLost

    private void descricaoProduto2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descricaoProduto2KeyReleased
        String input = descricaoProduto2.getText();

        // Remover todos os caracteres não alfabéticos
        input = input.replaceAll("[^\\p{L} ]", "");
        descricaoProduto2.setText(input);
    }//GEN-LAST:event_descricaoProduto2KeyReleased

    private void idProduto2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idProduto2FocusGained
        if (idProduto2.getText().equals("0")) {
            idProduto2.setText("");
            idProduto2.setForeground(Color.black);
        }
    }//GEN-LAST:event_idProduto2FocusGained

    private void idProduto2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idProduto2FocusLost
        if (idProduto2.getText().equals("")) {
            idProduto2.setText("0");
            idProduto2.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_idProduto2FocusLost

    private void idProduto2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idProduto2KeyReleased
        String input = idProduto2.getText();

        // Remover todos os caracteres não numéricos
        input = input.replaceAll("[^\\d]", "");
        idProduto2.setText(input);
    }//GEN-LAST:event_idProduto2KeyReleased

    private void valorProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorProduto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorProduto1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutosCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutosCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutosCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutosCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutosCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField descricaoProduto1;
    private javax.swing.JTextField descricaoProduto2;
    private javax.swing.JTextField idProduto1;
    private javax.swing.JTextField idProduto2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField nomeProduto1;
    private javax.swing.JTextField nomeProduto2;
    private javax.swing.JTextField quantidadeProduto1;
    private javax.swing.JTextField quantidadeProduto2;
    private javax.swing.JTextField valorProduto1;
    private javax.swing.JTextField valorProduto2;
    // End of variables declaration//GEN-END:variables
}
